local ClothingModule = {}

ClothingModule.Assets = {
    Starter = {
        Shirt = { id = "http://www.roblox.com/asset/?id=5943080475" },
        Pants = { id = "http://www.roblox.com/asset/?id=5938460797" },
    },

    Oathsworn = {
        Shirt = { id = "http://www.roblox.com/asset/?id=5833998366" },
        Pants = { id = "http://www.roblox.com/asset/?id=5833741855" },
    },

    Gaurd = {
        Shirt = { id = "http://www.roblox.com/asset/?id=7121925516" },
        Pants = { id = "http://www.roblox.com/asset/?id=7121973336" },
    },

    Stargazer = {
        Shirt = { id = "http://www.roblox.com/asset/?id=10420886700" },
        Pants = { id = "http://www.roblox.com/asset/?id=10420911360" },
    },
}

return ClothingModule