local StatusModule = {}

StatusModule.Combat = {
    "Stunned",
    "Dazed",
    "Equipped",
    "Parrying",
    "Blocking",
    "Attacking",
    "Parried",
    "Critical"
}

StatusModule.Movement = {
    "Running",
    "Dodging",
    "Wallrunning",
    "Leaping",
    "Hanging",
    "Climbing"
}

StatusModule.Interaction = {
    "Ragdoll"
}

StatusModule.Cooldown = {
    "Attack",
    "Aerial",
    "Lunge",
    "Stomp",
    "Dodge",
    "Critical",
    "Climb"
}

return StatusModule