--[[ BodyModule
    @author @Daystopia
    @version 1.0.0
    @date 2025-04-10
]]
local BodyModule = {}

BodyModule.SkinColors = {
	["Ivory"] = "#F4D7C5",
	["Sunkiss"] = "#EAC0A2",
	["Amber"] = "#D8A07F",
	["Ember"] = "#B97C5A",
	["Umber"] = "#8D5A3B",
	["Dusk"] = "#5E3B22",
	["Obsidian"] = "#3B2414",
	["Iron"] = "#8B8B8B",
	["Phantom"] = "#A0A0A0",
	["Azure"] = "#3B82F6",
	["Void"] = "#7A3BF6",
	["Verdant"] = "#4CAF50",
	["Crimson"] = "#D32F2F"
}

BodyModule.SkinIndex = {
	"Ivory", "Sunkiss", "Amber", "Ember", "Umber", "Dusk", "Obsidian", "Iron", "Phantom", "Azure", "Void", "Verdant", "Crimson"
}

return BodyModule