--[[ NameModule
    @author @Daystopia
    @version 1.0.0
    @date 2025-04-10
]]
local NameModule = {}

NameModule.FirstName = {
	"Aeris", "Cailen", "Calis", "Dain", "Draven", "Dusk", "Eldrin", "Elis", "Ephir", "Ephros", "Eryn",
	"Kael", "Lior", "Lucien", "Mael", "Malrik", "Myrris", "Neris", "Nyx", "Omren", "Orin", "Oris", "Oryn",
	"Quorin", "Rhadis", "Riven", "Sable", "Selis", "Selric", "Seris", "Solren", "Sorin", "Talon", "Thorne",
	"Tyrren", "Vael", "Vaelis", "Varen", "Varis", "Vayne", "Veyra", "Vexis", "Xalith", "Xyrel", "Zael",
	"Zareth", "Zephir", "Zyphor", "Zyren", "Zytheris"
}

NameModule.LastName = {
	"Ashen", "Blacke", "Blooden", "Cinder", "Crowe", "Darke", "Drayth", "Dreaden", "Duskir", "Duskrin",
	"Duskwind", "Ebonis", "Ebonshade", "Eldmour", "Everis", "Fallow", "Frost", "Gloam", "Graves", "Grimor",
	"Hollow", "Ironis", "Malveil", "Morvain", "Mythral", "Nether", "Nighten", "Noctis", "Omen", "Raveth",
	"Ravyn", "Sablethorn", "Shadow", "Storme", "Tensith", "Tenris", "Umbren", "Umbros", "Vaelix", "Vaelor",
	"Vaelth", "Vexir", "Veythorne", "Voidis", "Wraith", "Zephiral", "Zephiron", "Zypheris"
}

return NameModule
